# templates/secret.yaml
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  labels:
    app: {{ .Values.app.name }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets.stringData | nindent 2 }}
{{- end }}